/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of IssueUsage entities.
 * @param count 
 * @param href 
 * @param issueUsage 
 */
data class IssuesUsages(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("issueUsage") val issueUsage: List<IssueUsage>? = null
) : ListEntity<IssueUsage>() {
    @Transient private val classModelName: String = "issuesUsages"

    override fun items(): List<IssueUsage> {
        if (issueUsage == null)
            return emptyList()
        return issueUsage
    }


}

