/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a relation between issue and Changes entity.
 * @param issue 
 * @param changes 
 */
data class IssueUsage(
    @SerializedName("issue") val issue: Issue? = null,
    @SerializedName("changes") val changes: Changes? = null
) : DataEntity() {
    @Transient private val classModelName: String = "IssueUsage"


}

