/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of Agent entities.
 * @param count 
 * @param nextHref 
 * @param prevHref 
 * @param href 
 * @param agent 
 */
data class Agents(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("agent") val agent: List<Agent>? = null
) : PaginatedEntity<Agent>() {
    @Transient private val classModelName: String = "agents"

    override fun items(): List<Agent> {
        if (agent == null)
            return emptyList()
        return agent
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): Agents {
        val response = apiClient.request<Agents>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

