/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of AgentPool entities.
 * @param count 
 * @param href 
 * @param nextHref 
 * @param prevHref 
 * @param agentPool 
 */
data class AgentPools(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("agentPool") val agentPool: List<AgentPool>? = null
) : PaginatedEntity<AgentPool>() {
    @Transient private val classModelName: String = "agentPools"

    override fun items(): List<AgentPool> {
        if (agentPool == null)
            return emptyList()
        return agentPool
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): AgentPools {
        val response = apiClient.request<AgentPools>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

