/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an agent pool instance.
Related Help article: [Agent Pool](https://www.jetbrains.com/help/teamcity/agent-pool.html)
 * @param id 
 * @param name 
 * @param href 
 * @param maxAgents 
 * @param ownerProject 
 * @param projects 
 * @param agents 
 * @param locator 
 */
data class AgentPool(
    @SerializedName("id") val id: Int? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("maxAgents") val maxAgents: Int? = null,
    @SerializedName("ownerProject") val ownerProject: Project? = null,
    @SerializedName("projects") val projects: Projects? = null,
    @SerializedName("agents") val agents: Agents? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "agentPool"


}

