/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Compatibility entities.
 * @param count 
 * @param compatibility 
 */
data class Compatibilities(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("compatibility") val compatibility: List<Compatibility>? = null
) : ListEntity<Compatibility>() {
    @Transient private val classModelName: String = "compatibilities"

    override fun items(): List<Compatibility> {
        if (compatibility == null)
            return emptyList()
        return compatibility
    }


}

