/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents build configuration run policy and included build configurations.
 * @param policy 
 * @param buildTypes 
 */
data class CompatibilityPolicy(
    @SerializedName("policy") val policy: String? = null,
    @SerializedName("buildTypes") val buildTypes: BuildTypes? = null
) : DataEntity() {
    @Transient private val classModelName: String = "compatibilityPolicy"


}

