/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents OS details of the agent.
 * @param osType 
 * @param osName 
 */
data class Environment(
    @SerializedName("osType") val osType: String? = null,
    @SerializedName("osName") val osName: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "environment"


}

