/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of BuildChange entities.
 * @param count 
 * @param buildChange 
 */
data class BuildChanges(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("buildChange") val buildChange: List<BuildChange>? = null
) : ListEntity<BuildChange>() {
    @Transient private val classModelName: String = "buildChanges"

    override fun items(): List<BuildChange> {
        if (buildChange == null)
            return emptyList()
        return buildChange
    }


}

