/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents links on next or previous build
 * @param nextBuild 
 * @param prevBuild 
 */
data class BuildChange(
    @SerializedName("nextBuild") val nextBuild: Build? = null,
    @SerializedName("prevBuild") val prevBuild: Build? = null
) : DataEntity() {
    @Transient private val classModelName: String = "buildChange"


}

