/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a VCS change (commit).
Related Help article: [Change](https://www.jetbrains.com/help/teamcity/change.html)
 * @param id 
 * @param version 
 * @param internalVersion 
 * @param username 
 * @param date 
 * @param registrationDate 
 * @param personal 
 * @param href 
 * @param webUrl 
 * @param comment 
 * @param user 
 * @param files 
 * @param vcsRootInstance 
 * @param parentChanges 
 * @param parentRevisions 
 * @param attributes 
 * @param storesProjectSettings 
 * @param locator 
 */
data class Change(
    @SerializedName("id") val id: Long? = null,
    @SerializedName("version") val version: String? = null,
    @SerializedName("internalVersion") val internalVersion: String? = null,
    @SerializedName("username") val username: String? = null,
    @SerializedName("date") val date: String? = null,
    @SerializedName("registrationDate") val registrationDate: String? = null,
    @SerializedName("personal") val personal: Boolean? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("webUrl") val webUrl: String? = null,
    @SerializedName("comment") val comment: String? = null,
    @SerializedName("user") val user: User? = null,
    @SerializedName("files") val files: FileChanges? = null,
    @SerializedName("vcsRootInstance") val vcsRootInstance: VcsRootInstance? = null,
    @SerializedName("parentChanges") val parentChanges: Changes? = null,
    @SerializedName("parentRevisions") val parentRevisions: Items? = null,
    @SerializedName("attributes") val attributes: Properties? = null,
    @SerializedName("storesProjectSettings") val storesProjectSettings: Boolean? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "change"


}

