/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a specific file change (in scope of the commit).
 * @param beforeRevision 
 * @param afterRevision 
 * @param changeType 
 * @param changeTypeComment 
 * @param file 
 * @param relativeFile 
 * @param directory 
 */
data class FileChange(
    @SerializedName("before-revision") val beforeRevision: String? = null,
    @SerializedName("after-revision") val afterRevision: String? = null,
    @SerializedName("changeType") val changeType: String? = null,
    @SerializedName("changeTypeComment") val changeTypeComment: String? = null,
    @SerializedName("file") val file: String? = null,
    @SerializedName("relative-file") val relativeFile: String? = null,
    @SerializedName("directory") val directory: Boolean? = null
) : DataEntity() {
    @Transient private val classModelName: String = "FileChange"


}

