/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Branch entities.
 * @param timestamp 
 * @param count 
 * @param branch 
 */
data class RepositoryState(
    @SerializedName("timestamp") val timestamp: String? = null,
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("branch") val branch: List<BranchVersion>? = null
) : ListEntity<BranchVersion>() {
    @Transient private val classModelName: String = "repositoryState"

    override fun items(): List<BranchVersion> {
        if (branch == null)
            return emptyList()
        return branch
    }


}

