/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a revision related to a VCS change.
Related Help article: [Revision](https://www.jetbrains.com/help/teamcity/revision.html)
 * @param version 
 * @param internalVersion 
 * @param vcsBranchName 
 * @param vcsRootInstance 
 * @param checkoutRules 
 */
data class Revision(
    @SerializedName("version") val version: String? = null,
    @SerializedName("internalVersion") val internalVersion: String? = null,
    @SerializedName("vcsBranchName") val vcsBranchName: String? = null,
    @SerializedName("vcs-root-instance") val vcsRootInstance: VcsRootInstance? = null,
    @SerializedName("checkout-rules") val checkoutRules: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "Revision"


}

