/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Revision entities.
 * @param count 
 * @param revision 
 */
data class Revisions(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("revision") val revision: List<Revision>? = null
) : ListEntity<Revision>() {
    @Transient private val classModelName: String = "Revisions"

    override fun items(): List<Revision> {
        if (revision == null)
            return emptyList()
        return revision
    }


}

