/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents last known repository check status.
Related Help article: [VCS Root](https://www.jetbrains.com/help/teamcity/configuring-vcs-roots.html)
 * @param status 
 * @param requestorType 
 * @param timestamp 
 */
data class VcsCheckStatus(
    @SerializedName("status") val status: String? = null,
    @SerializedName("requestorType") val requestorType: String? = null,
    @SerializedName("timestamp") val timestamp: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "VcsCheckStatus"


}

