/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a relation between VCS root and unique settings set for this root.
Related Help article: [VCS Settings](https://www.jetbrains.com/help/teamcity/configuring-vcs-settings.html#VCS+Settings+Overview)
 * @param id 
 * @param vcsRootId 
 * @param vcsRootInternalId 
 * @param name 
 * @param vcsName 
 * @param modificationCheckInterval 
 * @param commitHookMode 
 * @param lastVersion 
 * @param lastVersionInternal 
 * @param href 
 * @param vcsRoot 
 * @param status 
 * @param repositoryState 
 * @param properties 
 * @param repositoryIdStrings 
 * @param projectLocator 
 */
data class VcsRootInstance(
    @SerializedName("id") val id: String? = null,
    @SerializedName("vcs-root-id") val vcsRootId: String? = null,
    @SerializedName("vcsRootInternalId") val vcsRootInternalId: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("vcsName") val vcsName: String? = null,
    @SerializedName("modificationCheckInterval") val modificationCheckInterval: Int? = null,
    @SerializedName("commitHookMode") val commitHookMode: Boolean? = null,
    @SerializedName("lastVersion") val lastVersion: String? = null,
    @SerializedName("lastVersionInternal") val lastVersionInternal: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("vcs-root") val vcsRoot: VcsRoot? = null,
    @SerializedName("status") val status: VcsStatus? = null,
    @SerializedName("repositoryState") val repositoryState: RepositoryState? = null,
    @SerializedName("properties") val properties: Properties? = null,
    @SerializedName("repositoryIdStrings") val repositoryIdStrings: Items? = null,
    @SerializedName("projectLocator") val projectLocator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "vcs-root-instance"


}

