/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a VCS root.
Related Help article: [VCS Root](https://www.jetbrains.com/help/teamcity/vcs-root.html)
 * @param id 
 * @param internalId 
 * @param uuid 
 * @param name 
 * @param vcsName 
 * @param modificationCheckInterval 
 * @param href 
 * @param project 
 * @param properties 
 * @param vcsRootInstances 
 * @param repositoryIdStrings 
 * @param projectLocator 
 * @param locator 
 */
data class VcsRoot(
    @SerializedName("id") val id: String? = null,
    @SerializedName("internalId") val internalId: String? = null,
    @SerializedName("uuid") val uuid: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("vcsName") val vcsName: String? = null,
    @SerializedName("modificationCheckInterval") val modificationCheckInterval: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("project") val project: Project? = null,
    @SerializedName("properties") val properties: Properties? = null,
    @SerializedName("vcsRootInstances") val vcsRootInstances: VcsRootInstances? = null,
    @SerializedName("repositoryIdStrings") val repositoryIdStrings: Items? = null,
    @SerializedName("projectLocator") val projectLocator: String? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "vcs-root"


}

