/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Entry entities.
 * @param count 
 * @param entry 
 */
data class Entries(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("entry") val entry: List<Entry>? = null
) : ListEntity<Entry>() {
    @Transient private val classModelName: String = "entries"

    override fun items(): List<Entry> {
        if (entry == null)
            return emptyList()
        return entry
    }


}

