/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Property entities.
 * @param count 
 * @param href 
 * @param property 
 */
data class Properties(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("property") val property: List<Property>? = null
) : ListEntity<Property>() {
    @Transient private val classModelName: String = "properties"

    override fun items(): List<Property> {
        if (property == null)
            return emptyList()
        return property
    }


}

