/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Entity entities.
 * @param count 
 * @param entity 
 */
data class RelatedEntities(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("entity") val entity: List<RelatedEntity>? = null
) : ListEntity<RelatedEntity>() {
    @Transient private val classModelName: String = "relatedEntities"

    override fun items(): List<RelatedEntity> {
        if (entity == null)
            return emptyList()
        return entity
    }


}

