/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering Agent entities.
Examples:
* `name:DefaultAgent` – find agent with DefaultAgent name.
* `pool:(<agentPoolLocator>),connected:true` – find all connected agents in a pool found by agentPoolLocator.
 * @param singleValue Return a single value.
 * @param authorized Is the agent authorized.
 * @param build Build locator.
 * @param compatible Compatible build types locator.
 * @param connected Is the agent connected.
 * @param count For paginated calls, how many entities to return per page.
 * @param enabled Is the agent enabled.
 * @param id Entity ID.
 * @param ip 
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param name 
 * @param parameter 
 * @param pool Agent pool ID.
 * @param start For paginated calls, from which entity to start rendering the page.
 */
class AgentLocator(
    @SerializedName("\$singleValue") val singleValue: Boolean? = null,
    @SerializedName("authorized") val authorized: Boolean? = null,
    @SerializedName("build") val build: String? = null,
    @SerializedName("compatible") val compatible: String? = null,
    @SerializedName("connected") val connected: Boolean? = null,
    @SerializedName("count") val count: Int? = null,
    @SerializedName("enabled") val enabled: Boolean? = null,
    @SerializedName("id") val id: Int? = null,
    @SerializedName("ip") val ip: String? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("parameter") val parameter: String? = null,
    @SerializedName("pool") val pool: String? = null,
    @SerializedName("start") val start: Int? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "AgentLocator"


}

