/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering AuditEvent entities.
Examples:
* `count:1000` – find last 1000 audit events.
* `user:(<userLocator>)` – find last 100 events by user found by userLocator.
 * @param action Use `$help` to get the full list of supported actions.
 * @param affectedProject Related project locator.
 * @param buildType Related build type or template locator.
 * @param count For paginated calls, how many entities to return per page.
 * @param id 
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param lookupLimit Limit processing to the latest `<lookupLimit>` entities.
 * @param start For paginated calls, from which entity to start rendering the page.
 * @param systemAction 
 * @param user Locator of user who caused the audit event.
 */
class AuditLocator(
    @SerializedName("action") val action: String? = null,
    @SerializedName("affectedProject") val affectedProject: String? = null,
    @SerializedName("buildType") val buildType: String? = null,
    @SerializedName("count") val count: Int? = null,
    @SerializedName("id") val id: String? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("lookupLimit") val lookupLimit: Int? = null,
    @SerializedName("start") val start: Int? = null,
    @SerializedName("systemAction") val systemAction: String? = null,
    @SerializedName("user") val user: String? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "AuditLocator"


}

