/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering Branch entities.
Examples:
* `build:<buildLocator>` – find branch with which the build found by buildLocator was started.
* `buildType:<buildTypeLocator>` – find branches of a build configuration found by buildTypeLocator.
 * @param branched Is feature branch.
 * @param build Build locator.
 * @param buildType Build type locator.
 * @param default Is default branch.
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param name 
 */
class BranchLocator(
    @SerializedName("branched") val branched: String? = null,
    @SerializedName("build") val build: String? = null,
    @SerializedName("buildType") val buildType: String? = null,
    @SerializedName("default") val default: String? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("name") val name: String? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "BranchLocator"


}

