/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering Change entities.
Examples:
* `username:MyVCSUsername` – find last 100 changes made by user with MyVCSUsername VCS username.
* `pending:true,buildType:<buildTypeLocator>` – find all pending changes on build configuration found by buildTypeLocator.
 * @param singleValue Return a single value.
 * @param build Build locator.
 * @param buildType Build type locator.
 * @param comment 
 * @param count For paginated calls, how many entities to return per page.
 * @param file 
 * @param id Entity ID.
 * @param internalVersion 
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param pending Is pending.
 * @param project Project locator.
 * @param sinceChange Commit SHA since which the changes should be returned.
 * @param start For paginated calls, from which entity to start rendering the page.
 * @param user User locator.
 * @param username VCS side username.
 * @param vcsRoot VCS root locator.
 * @param vcsRootInstance VCS instance locator.
 * @param version 
 */
class ChangeLocator(
    @SerializedName("\$singleValue") val singleValue: Boolean? = null,
    @SerializedName("build") val build: String? = null,
    @SerializedName("buildType") val buildType: String? = null,
    @SerializedName("comment") val comment: String? = null,
    @SerializedName("count") val count: Int? = null,
    @SerializedName("file") val file: String? = null,
    @SerializedName("id") val id: Int? = null,
    @SerializedName("internalVersion") val internalVersion: String? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("pending") val pending: Boolean? = null,
    @SerializedName("project") val project: String? = null,
    @SerializedName("sinceChange") val sinceChange: String? = null,
    @SerializedName("start") val start: Int? = null,
    @SerializedName("user") val user: String? = null,
    @SerializedName("username") val username: String? = null,
    @SerializedName("vcsRoot") val vcsRoot: String? = null,
    @SerializedName("vcsRootInstance") val vcsRootInstance: String? = null,
    @SerializedName("version") val version: String? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "ChangeLocator"


}

