/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering Mute entities.
Examples:
* `project:<projectLocator>` – find muted problem under project found by projectLocator.
* `type:test` – find last 100 muted tests.
 * @param affectedProject Project (direct or indirect parent) locator.
 * @param creationDate yyyyMMddTHHmmss+ZZZZ
 * @param id 
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param problem Problem locator.
 * @param project Project (direct parent) locator.
 * @param reporter User who muted this test.
 * @param resolution Supported values: manually/whenFixed/atTime.
 * @param test Test locator.
 * @param type Supported values: test/problem/anyProblem/unknown.
 * @param unmuteDate yyyyMMddTHHmmss+ZZZZ
 */
class MuteLocator(
    @SerializedName("affectedProject") val affectedProject: String? = null,
    @SerializedName("creationDate") val creationDate: LocalDateTime? = null,
    @SerializedName("id") val id: Int? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("problem") val problem: String? = null,
    @SerializedName("project") val project: String? = null,
    @SerializedName("reporter") val reporter: String? = null,
    @SerializedName("resolution") val resolution: String? = null,
    @SerializedName("test") val test: String? = null,
    @SerializedName("type") val type: String? = null,
    @SerializedName("unmuteDate") val unmuteDate: LocalDateTime? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "MuteLocator"


}

