/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**

 * @param name 
 * @param owner 
 * @param &#x60;Private&#x60; 
 */
class TagLocator(
    @SerializedName("name") val name: String? = null,
    @SerializedName("owner") val owner: String? = null,
    @SerializedName("private") val `Private`: String? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "TagLocator"


}

