/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering UserGroup entities.
Examples:
* 'name:MyGroupName' – find group with name MyGroupName.
* 'key:MyGroupKey' – find group with key MyGroupKey.
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param key 
 * @param name 
 */
class UserGroupLocator(
    @SerializedName("item") val item: String? = null,
    @SerializedName("key") val key: String? = null,
    @SerializedName("name") val name: String? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "UserGroupLocator"


}

