/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a locator string for filtering VcsRootInstance entities.
Examples:
* `vcsRoot:<vcsRootLocator>` – find all VCS root instances of a VCS root found by vcsRootLocator.
* `project:<projectLocator>` – find all VCS root instances defined under project found by projectLocator.
 * @param singleValue Return a single value.
 * @param affectedProject Project (direct or indirect parent) locator.
 * @param build Build locator.
 * @param buildType Build type locator.
 * @param count For paginated calls, how many entities to return per page.
 * @param id Entity ID.
 * @param item [EXPERIMENTAL] Supply multiple locators and return a union of the results.
 * @param lookupLimit Limit processing to the latest `<lookupLimit>` entities.
 * @param project Project (direct parent) locator.
 * @param property Supported matchType values: 
- generic: exists/not-exists/equals/does-not-equal/starts-with/contains/does-not-contain/ends-with/any; 
- regular expressions: matches/does-not-match; 
- numeric: more-than/no-more-than/less-than/no-less-than; 
- version-specific: ver-more-than/ver-no-more-than/ver-less-than/ver-no-less-than.
 * @param start For paginated calls, from which entity to start rendering the page.
 * @param type Type of VCS (e.g. jetbrains.git).
 * @param vcsRoot VCS root locator.
 * @param versionedSettings Is used for versioned settings.
 */
class VcsRootInstanceLocator(
    @SerializedName("\$singleValue") val singleValue: Boolean? = null,
    @SerializedName("affectedProject") val affectedProject: String? = null,
    @SerializedName("build") val build: String? = null,
    @SerializedName("buildType") val buildType: String? = null,
    @SerializedName("count") val count: Int? = null,
    @SerializedName("id") val id: Int? = null,
    @SerializedName("item") val item: String? = null,
    @SerializedName("lookupLimit") val lookupLimit: Int? = null,
    @SerializedName("project") val project: String? = null,
    @SerializedName("property") val property: String? = null,
    @SerializedName("start") val start: Int? = null,
    @SerializedName("type") val type: String? = null,
    @SerializedName("vcsRoot") val vcsRoot: String? = null,
    @SerializedName("versionedSettings") val versionedSettings: Boolean? = null
) : LocatorEntity() {
    @Transient private val classModelName: String = "VcsRootInstanceLocator"


}

