/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of AuditEvent entities.
 * @param count 
 * @param nextHref 
 * @param prevHref 
 * @param href 
 * @param auditEvent 
 */
data class AuditEvents(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("auditEvent") val auditEvent: List<AuditEvent>? = null
) : PaginatedEntity<AuditEvent>() {
    @Transient private val classModelName: String = "auditEvents"

    override fun items(): List<AuditEvent> {
        if (auditEvent == null)
            return emptyList()
        return auditEvent
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): AuditEvents {
        val response = apiClient.request<AuditEvents>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

