/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an audit event including user and affected entities.
Related Help article: [Audit](https://www.jetbrains.com/help/teamcity/tracking-user-actions.html)
 * @param id 
 * @param timestamp 
 * @param comment 
 * @param action 
 * @param relatedEntities 
 * @param user 
 */
data class AuditEvent(
    @SerializedName("id") val id: String? = null,
    @SerializedName("timestamp") val timestamp: String? = null,
    @SerializedName("comment") val comment: String? = null,
    @SerializedName("action") val action: AuditAction? = null,
    @SerializedName("relatedEntities") val relatedEntities: RelatedEntities? = null,
    @SerializedName("user") val user: User? = null
) : DataEntity() {
    @Transient private val classModelName: String = "auditEvent"


}

