/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an audit action.
Related Help article: [Audit](https://www.jetbrains.com/help/teamcity/tracking-user-actions.html)
 * @param name 
 * @param id 
 * @param pattern 
 */
data class AuditAction(
    @SerializedName("name") val name: String? = null,
    @SerializedName("id") val id: String? = null,
    @SerializedName("pattern") val pattern: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "auditAction"


}

