/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Metric entities.
 * @param count 
 * @param metric 
 */
data class Metrics(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("metric") val metric: List<Metric>? = null
) : ListEntity<Metric>() {
    @Transient private val classModelName: String = "metrics"

    override fun items(): List<Metric> {
        if (metric == null)
            return emptyList()
        return metric
    }


}

