/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of MetricTag entities.
 * @param count 
 * @param metricTag 
 */
data class MetricTags(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("metricTag") val metricTag: List<MetricTag>? = null
) : ListEntity<MetricTag>() {
    @Transient private val classModelName: String = "metricTags"

    override fun items(): List<MetricTag> {
        if (metricTag == null)
            return emptyList()
        return metricTag
    }


}

