/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of MetricValue entities.
 * @param count 
 * @param metricValue 
 */
data class MetricValues(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("metricValue") val metricValue: List<MetricValue>? = null
) : ListEntity<MetricValue>() {
    @Transient private val classModelName: String = "metricValues"

    override fun items(): List<MetricValue> {
        if (metricValue == null)
            return emptyList()
        return metricValue
    }


}

