/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a specific server metric.
Related Help article: [Metrics](https://www.jetbrains.com/help/teamcity/teamcity-monitoring-and-diagnostics.html#Metrics)
 * @param name 
 * @param description 
 * @param prometheusName 
 * @param metricValues 
 * @param metricTags 
 */
data class Metric(
    @SerializedName("name") val name: String? = null,
    @SerializedName("description") val description: String? = null,
    @SerializedName("prometheusName") val prometheusName: String? = null,
    @SerializedName("metricValues") val metricValues: MetricValues? = null,
    @SerializedName("metricTags") val metricTags: MetricTags? = null
) : DataEntity() {
    @Transient private val classModelName: String = "metric"


}

