/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of File entities.
 * @param count 
 * @param href 
 * @param file 
 */
data class Files(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("file") val file: List<File>? = null
) : ListEntity<File>() {
    @Transient private val classModelName: String = "files"

    override fun items(): List<File> {
        if (file == null)
            return emptyList()
        return file
    }


}

