/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a user group.
Related Help article: [User Group](https://www.jetbrains.com/help/teamcity/user-group.html)
 * @param key 
 * @param name 
 * @param href 
 * @param description 
 * @param parentGroups 
 * @param childGroups 
 * @param users 
 * @param roles 
 * @param properties 
 */
data class Group(
    @SerializedName("key") val key: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("description") val description: String? = null,
    @SerializedName("parent-groups") val parentGroups: Groups? = null,
    @SerializedName("child-groups") val childGroups: Groups? = null,
    @SerializedName("users") val users: Users? = null,
    @SerializedName("roles") val roles: Roles? = null,
    @SerializedName("properties") val properties: Properties? = null
) : DataEntity() {
    @Transient private val classModelName: String = "group"


}

