/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Group entities.
 * @param count 
 * @param group 
 */
data class Groups(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("group") val group: List<Group>? = null
) : ListEntity<Group>() {
    @Transient private val classModelName: String = "groups"

    override fun items(): List<Group> {
        if (group == null)
            return emptyList()
        return group
    }


}

