/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Agent-requirement entities.
 * @param count 
 * @param agentRequirement 
 */
data class AgentRequirements(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("agent-requirement") val agentRequirement: List<AgentRequirement>? = null
) : ListEntity<AgentRequirement>() {
    @Transient private val classModelName: String = "agent-requirements"

    override fun items(): List<AgentRequirement> {
        if (agentRequirement == null)
            return emptyList()
        return agentRequirement
    }


}

