/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of BuildType entities.
 * @param count 
 * @param href 
 * @param nextHref 
 * @param prevHref 
 * @param buildType 
 */
data class BuildTypes(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("buildType") val buildType: List<BuildType>? = null
) : PaginatedEntity<BuildType>() {
    @Transient private val classModelName: String = "buildTypes"

    override fun items(): List<BuildType> {
        if (buildType == null)
            return emptyList()
        return buildType
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): BuildTypes {
        val response = apiClient.request<BuildTypes>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

