/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Feature entities.
 * @param count 
 * @param feature 
 */
data class Features(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("feature") val feature: List<Feature>? = null
) : ListEntity<Feature>() {
    @Transient private val classModelName: String = "features"

    override fun items(): List<Feature> {
        if (feature == null)
            return emptyList()
        return feature
    }


}

