/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an investigation on build problem.
 * @param id 
 * @param state 
 * @param href 
 * @param assignee 
 * @param assignment 
 * @param scope 
 * @param target 
 * @param resolution 
 * @param responsible 
 */
data class Investigation(
    @SerializedName("id") val id: String? = null,
    @SerializedName("state") val state: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("assignee") val assignee: User? = null,
    @SerializedName("assignment") val assignment: Comment? = null,
    @SerializedName("scope") val scope: ProblemScope? = null,
    @SerializedName("target") val target: ProblemTarget? = null,
    @SerializedName("resolution") val resolution: Resolution? = null,
    @SerializedName("responsible") val responsible: User? = null
) : DataEntity() {
    @Transient private val classModelName: String = "investigation"


}

