/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of Investigation entities.
 * @param count 
 * @param nextHref 
 * @param prevHref 
 * @param href 
 * @param investigation 
 */
data class Investigations(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("investigation") val investigation: List<Investigation>? = null
) : PaginatedEntity<Investigation>() {
    @Transient private val classModelName: String = "investigations"

    override fun items(): List<Investigation> {
        if (investigation == null)
            return emptyList()
        return investigation
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): Investigations {
        val response = apiClient.request<Investigations>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

