/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an investigation target.
 * @param anyProblem 
 * @param tests 
 * @param problems 
 */
data class ProblemTarget(
    @SerializedName("anyProblem") val anyProblem: Boolean? = null,
    @SerializedName("tests") val tests: Tests? = null,
    @SerializedName("problems") val problems: Problems? = null
) : DataEntity() {
    @Transient private val classModelName: String = "ProblemTarget"


}

