/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an investigation scope.
 * @param project 
 * @param buildTypes 
 * @param buildType 
 */
data class ProblemScope(
    @SerializedName("project") val project: Project? = null,
    @SerializedName("buildTypes") val buildTypes: BuildTypes? = null,
    @SerializedName("buildType") val buildType: BuildType? = null
) : DataEntity() {
    @Transient private val classModelName: String = "ProblemScope"


}

