/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Snapshot-dependency entities.
 * @param count 
 * @param snapshotDependency 
 */
data class SnapshotDependencies(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("snapshot-dependency") val snapshotDependency: List<SnapshotDependency>? = null
) : ListEntity<SnapshotDependency>() {
    @Transient private val classModelName: String = "snapshot-dependencies"

    override fun items(): List<SnapshotDependency> {
        if (snapshotDependency == null)
            return emptyList()
        return snapshotDependency
    }


}

