/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Step entities.
 * @param count 
 * @param step 
 */
data class Steps(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("step") val step: List<Step>? = null
) : ListEntity<Step>() {
    @Transient private val classModelName: String = "steps"

    override fun items(): List<Step> {
        if (step == null)
            return emptyList()
        return step
    }


}

