/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of Vcs-root-instance entities.
 * @param count 
 * @param href 
 * @param nextHref 
 * @param prevHref 
 * @param vcsRootInstance 
 */
data class VcsRootInstances(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("vcs-root-instance") val vcsRootInstance: List<VcsRootInstance>? = null
) : PaginatedEntity<VcsRootInstance>() {
    @Transient private val classModelName: String = "vcs-root-instances"

    override fun items(): List<VcsRootInstance> {
        if (vcsRootInstance == null)
            return emptyList()
        return vcsRootInstance
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): VcsRootInstances {
        val response = apiClient.request<VcsRootInstances>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

