/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a VCS root assigned to this build configuration.
 * @param id 
 * @param inherited 
 * @param vcsRoot 
 * @param checkoutRules 
 */
data class VcsRootEntry(
    @SerializedName("id") val id: String? = null,
    @SerializedName("inherited") val inherited: Boolean? = null,
    @SerializedName("vcs-root") val vcsRoot: VcsRoot? = null,
    @SerializedName("checkout-rules") val checkoutRules: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "vcs-root-entry"


}

