/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Vcs-root-entry entities.
 * @param count 
 * @param vcsRootEntry 
 */
data class VcsRootEntries(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("vcs-root-entry") val vcsRootEntry: List<VcsRootEntry>? = null
) : ListEntity<VcsRootEntry>() {
    @Transient private val classModelName: String = "vcs-root-entries"

    override fun items(): List<VcsRootEntry> {
        if (vcsRootEntry == null)
            return emptyList()
        return vcsRootEntry
    }


}

