/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a muted test.
 * @param id 
 * @param href 
 * @param assignment 
 * @param scope 
 * @param target 
 * @param resolution 
 */
data class Mute(
    @SerializedName("id") val id: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("assignment") val assignment: Comment? = null,
    @SerializedName("scope") val scope: ProblemScope? = null,
    @SerializedName("target") val target: ProblemTarget? = null,
    @SerializedName("resolution") val resolution: Resolution? = null
) : DataEntity() {
    @Transient private val classModelName: String = "mute"


}

