/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents test metadata (package, method, class, etc.).
 * @param testPackage 
 * @param testSuite 
 * @param testClass 
 * @param testShortName 
 * @param testNameWithoutPrefix 
 * @param testMethodName 
 * @param testNameWithParameters 
 */
data class ParsedTestName(
    @SerializedName("testPackage") val testPackage: String? = null,
    @SerializedName("testSuite") val testSuite: String? = null,
    @SerializedName("testClass") val testClass: String? = null,
    @SerializedName("testShortName") val testShortName: String? = null,
    @SerializedName("testNameWithoutPrefix") val testNameWithoutPrefix: String? = null,
    @SerializedName("testMethodName") val testMethodName: String? = null,
    @SerializedName("testNameWithParameters") val testNameWithParameters: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "ParsedTestName"


}

