/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents instance of failed test in specific build.
 * @param id 
 * @param type 
 * @param identity 
 * @param href 
 * @param muted 
 * @param currentlyInvestigated 
 * @param currentlyMuted 
 * @param logAnchor 
 * @param newFailure 
 * @param details 
 * @param additionalData 
 * @param problem 
 * @param mute 
 * @param build 
 */
data class ProblemOccurrence(
    @SerializedName("id") val id: String? = null,
    @SerializedName("type") val type: String? = null,
    @SerializedName("identity") val identity: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("muted") val muted: Boolean? = null,
    @SerializedName("currentlyInvestigated") val currentlyInvestigated: Boolean? = null,
    @SerializedName("currentlyMuted") val currentlyMuted: Boolean? = null,
    @SerializedName("logAnchor") val logAnchor: String? = null,
    @SerializedName("newFailure") val newFailure: Boolean? = null,
    @SerializedName("details") val details: String? = null,
    @SerializedName("additionalData") val additionalData: String? = null,
    @SerializedName("problem") val problem: Problem? = null,
    @SerializedName("mute") val mute: Mute? = null,
    @SerializedName("build") val build: Build? = null
) : DataEntity() {
    @Transient private val classModelName: String = "problemOccurrence"


}

