/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an issue with test.
 * @param id 
 * @param type 
 * @param identity 
 * @param href 
 * @param description 
 * @param mutes 
 * @param investigations 
 * @param problemOccurrences 
 * @param locator 
 */
data class Problem(
    @SerializedName("id") val id: String? = null,
    @SerializedName("type") val type: String? = null,
    @SerializedName("identity") val identity: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("description") val description: String? = null,
    @SerializedName("mutes") val mutes: Mutes? = null,
    @SerializedName("investigations") val investigations: Investigations? = null,
    @SerializedName("problemOccurrences") val problemOccurrences: ProblemOccurrences? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "problem"


}

