/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of Test entities.
 * @param count 
 * @param myTestCounters 
 * @param nextHref 
 * @param prevHref 
 * @param test 
 */
data class Tests(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("myTestCounters") val myTestCounters: TestCounters? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("test") val test: List<Test>? = null
) : PaginatedEntity<Test>() {
    @Transient private val classModelName: String = "tests"

    override fun items(): List<Test> {
        if (test == null)
            return emptyList()
        return test
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): Tests {
        val response = apiClient.request<Tests>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

