/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of TypedValues entities.
 * @param count 
 * @param typedValues 
 */
data class TestRunMetadata(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("typedValues") val typedValues: List<TypedValue>? = null
) : ListEntity<TypedValue>() {
    @Transient private val classModelName: String = "testRunMetadata"

    override fun items(): List<TypedValue> {
        if (typedValues == null)
            return emptyList()
        return typedValues
    }


}

