/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**

 * @param ignored 
 * @param failed 
 * @param muted 
 * @param success 
 * @param all 
 */
data class TestCounters(
    @SerializedName("ignored") val ignored: Int? = null,
    @SerializedName("failed") val failed: Int? = null,
    @SerializedName("muted") val muted: Int? = null,
    @SerializedName("success") val success: Int? = null,
    @SerializedName("all") val all: Int? = null
) : DataEntity() {
    @Transient private val classModelName: String = "testCounters"


}

