/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of TestOccurrence entities.
 * @param count 
 * @param href 
 * @param nextHref 
 * @param prevHref 
 * @param testOccurrence 
 * @param testCounters 
 * @param passed 
 * @param failed 
 * @param newFailed 
 * @param ignored 
 * @param muted 
 */
data class TestOccurrences(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("testOccurrence") val testOccurrence: List<TestOccurrence>? = null,
    @SerializedName("testCounters") val testCounters: TestCounters? = null,
    @SerializedName("passed") val passed: Int? = null,
    @SerializedName("failed") val failed: Int? = null,
    @SerializedName("newFailed") val newFailed: Int? = null,
    @SerializedName("ignored") val ignored: Int? = null,
    @SerializedName("muted") val muted: Int? = null
) : PaginatedEntity<TestOccurrence>() {
    @Transient private val classModelName: String = "testOccurrences"

    override fun items(): List<TestOccurrence> {
        if (testOccurrence == null)
            return emptyList()
        return testOccurrence
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): TestOccurrences {
        val response = apiClient.request<TestOccurrences>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

