/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a relation between test and specific build.
 * @param id 
 * @param name 
 * @param status 
 * @param ignored 
 * @param duration 
 * @param runOrder 
 * @param newFailure 
 * @param muted 
 * @param currentlyMuted 
 * @param currentlyInvestigated 
 * @param href 
 * @param ignoreDetails 
 * @param details 
 * @param test 
 * @param mute 
 * @param build 
 * @param firstFailed 
 * @param nextFixed 
 * @param invocations 
 * @param metadata 
 * @param logAnchor 
 */
data class TestOccurrence(
    @SerializedName("id") val id: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("status") val status: String? = null,
    @SerializedName("ignored") val ignored: Boolean? = null,
    @SerializedName("duration") val duration: Int? = null,
    @SerializedName("runOrder") val runOrder: String? = null,
    @SerializedName("newFailure") val newFailure: Boolean? = null,
    @SerializedName("muted") val muted: Boolean? = null,
    @SerializedName("currentlyMuted") val currentlyMuted: Boolean? = null,
    @SerializedName("currentlyInvestigated") val currentlyInvestigated: Boolean? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("ignoreDetails") val ignoreDetails: String? = null,
    @SerializedName("details") val details: String? = null,
    @SerializedName("test") val test: Test? = null,
    @SerializedName("mute") val mute: Mute? = null,
    @SerializedName("build") val build: Build? = null,
    @SerializedName("firstFailed") val firstFailed: TestOccurrence? = null,
    @SerializedName("nextFixed") val nextFixed: TestOccurrence? = null,
    @SerializedName("invocations") val invocations: TestOccurrences? = null,
    @SerializedName("metadata") val metadata: TestRunMetadata? = null,
    @SerializedName("logAnchor") val logAnchor: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "testOccurrence"


}

