/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a paginated list of CloudImage entities.
 * @param count 
 * @param nextHref 
 * @param prevHref 
 * @param href 
 * @param cloudImage 
 */
data class CloudImages(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("nextHref") override val nextHref: String? = null,
    @SerializedName("prevHref") override val prevHref: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("cloudImage") val cloudImage: List<CloudImage>? = null
) : PaginatedEntity<CloudImage>() {
    @Transient private val classModelName: String = "cloudImages"

    override fun items(): List<CloudImage> {
        if (cloudImage == null)
            return emptyList()
        return cloudImage
    }

    override fun requestNextPage(apiClient: ApiClient, requestConfig: RequestConfig): CloudImages {
        val response = apiClient.request<CloudImages>(requestConfig)
        return ApiClient.processResponse(response)
    }

}

