/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a running cloud instance.
Related Help article: [Cloud Profile](https://www.jetbrains.com/help/teamcity/agent-cloud-profile.html)
 * @param id 
 * @param name 
 * @param state 
 * @param startDate 
 * @param networkAddress 
 * @param href 
 * @param image 
 * @param agent 
 * @param errorMessage 
 */
data class CloudInstance(
    @SerializedName("id") val id: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("state") val state: String? = null,
    @SerializedName("startDate") val startDate: String? = null,
    @SerializedName("networkAddress") val networkAddress: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("image") val image: CloudImage? = null,
    @SerializedName("agent") val agent: Agent? = null,
    @SerializedName("errorMessage") val errorMessage: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "cloudInstance"


}

