/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a cloud instance image saved with profile.
Related Help article: [Cloud Profile](https://www.jetbrains.com/help/teamcity/agent-cloud-profile.html)
 * @param id 
 * @param name 
 * @param href 
 * @param profile 
 * @param instances 
 * @param errorMessage 
 * @param agentTypeId 
 * @param locator 
 */
data class CloudImage(
    @SerializedName("id") val id: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("profile") val profile: CloudProfile? = null,
    @SerializedName("instances") val instances: CloudInstances? = null,
    @SerializedName("errorMessage") val errorMessage: String? = null,
    @SerializedName("agentTypeId") val agentTypeId: Int? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "cloudImage"


}

