/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
PluginInfo
 * @param name 
 * @param displayName 
 * @param version 
 * @param loadPath 
 * @param parameters 
 */
data class Plugin(
    @SerializedName("name") val name: String? = null,
    @SerializedName("displayName") val displayName: String? = null,
    @SerializedName("version") val version: String? = null,
    @SerializedName("loadPath") val loadPath: String? = null,
    @SerializedName("parameters") val parameters: Properties? = null
) : DataEntity() {
    @Transient private val classModelName: String = "plugin"


}

