/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents permission restrictions of an authentication token.
 * @param isGlobalScope 
 * @param project 
 * @param permission 
 */
data class PermissionRestriction(
    @SerializedName("isGlobalScope") val isGlobalScope: Boolean? = null,
    @SerializedName("project") val project: Project? = null,
    @SerializedName("permission") val permission: Permission? = null
) : DataEntity() {
    @Transient private val classModelName: String = "permissionRestriction"


}

