/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a permission.
Related Help article: [Roles](https://www.jetbrains.com/help/teamcity/role-and-permission.html)
 * @param id 
 * @param name 
 * @param global 
 */
data class Permission(
    @SerializedName("id") val id: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("global") val global: Boolean? = null
) : DataEntity() {
    @Transient private val classModelName: String = "permission"


}

