/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a relation between specific permission and project.
 * @param permission 
 * @param project 
 */
data class PermissionAssignment(
    @SerializedName("permission") val permission: Permission? = null,
    @SerializedName("project") val project: Project? = null
) : DataEntity() {
    @Transient private val classModelName: String = "permissionAssignment"


}

