/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
RoleAssignment
 * @param roleId 
 * @param scope 
 * @param href 
 */
data class Role(
    @SerializedName("roleId") val roleId: String? = null,
    @SerializedName("scope") val scope: String? = null,
    @SerializedName("href") override val href: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "role"


}

