/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents an authentication token.
 * @param name 
 * @param creationTime 
 * @param value 
 * @param expirationTime 
 * @param permissionRestrictions 
 */
data class Token(
    @SerializedName("name") val name: String? = null,
    @SerializedName("creationTime") val creationTime: LocalDateTime? = null,
    @SerializedName("value") val value: String? = null,
    @SerializedName("expirationTime") val expirationTime: LocalDateTime? = null,
    @SerializedName("permissionRestrictions") val permissionRestrictions: PermissionRestrictions? = null
) : DataEntity() {
    @Transient private val classModelName: String = "token"


}

