/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of Token entities.
 * @param count 
 * @param token 
 */
data class Tokens(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("token") val token: List<Token>? = null
) : ListEntity<Token>() {
    @Transient private val classModelName: String = "tokens"

    override fun items(): List<Token> {
        if (token == null)
            return emptyList()
        return token
    }


}

