/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of User entities.
 * @param count 
 * @param user 
 */
data class Users(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("user") val user: List<User>? = null
) : ListEntity<User>() {
    @Transient private val classModelName: String = "users"

    override fun items(): List<User> {
        if (user == null)
            return emptyList()
        return user
    }


}

