/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a user.
Related Help article: [User Account](https://www.jetbrains.com/help/teamcity/user-account.html)
 * @param username 
 * @param name 
 * @param id 
 * @param email 
 * @param lastLogin 
 * @param password 
 * @param hasPassword 
 * @param realm 
 * @param href 
 * @param properties 
 * @param roles 
 * @param groups 
 * @param locator 
 */
data class User(
    @SerializedName("username") val username: String? = null,
    @SerializedName("name") val name: String? = null,
    @SerializedName("id") val id: Long? = null,
    @SerializedName("email") val email: String? = null,
    @SerializedName("lastLogin") val lastLogin: String? = null,
    @SerializedName("password") val password: String? = null,
    @SerializedName("hasPassword") val hasPassword: Boolean? = null,
    @SerializedName("realm") val realm: String? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("properties") val properties: Properties? = null,
    @SerializedName("roles") val roles: Roles? = null,
    @SerializedName("groups") val groups: Groups? = null,
    @SerializedName("locator") val locator: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "user"


}

