/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a license key details.
 * @param valid 
 * @param active 
 * @param expired 
 * @param obsolete 
 * @param expirationDate 
 * @param maintenanceEndDate 
 * @param type 
 * @param servers 
 * @param agents 
 * @param unlimitedAgents 
 * @param buildTypes 
 * @param unlimitedBuildTypes 
 * @param errorDetails 
 * @param key 
 * @param rawType 
 */
data class LicenseKey(
    @SerializedName("valid") val valid: Boolean? = null,
    @SerializedName("active") val active: Boolean? = null,
    @SerializedName("expired") val expired: Boolean? = null,
    @SerializedName("obsolete") val obsolete: Boolean? = null,
    @SerializedName("expirationDate") val expirationDate: String? = null,
    @SerializedName("maintenanceEndDate") val maintenanceEndDate: String? = null,
    @SerializedName("type") val type: String? = null,
    @SerializedName("servers") val servers: Int? = null,
    @SerializedName("agents") val agents: Int? = null,
    @SerializedName("unlimitedAgents") val unlimitedAgents: Boolean? = null,
    @SerializedName("buildTypes") val buildTypes: Int? = null,
    @SerializedName("unlimitedBuildTypes") val unlimitedBuildTypes: Boolean? = null,
    @SerializedName("errorDetails") val errorDetails: String? = null,
    @SerializedName("key") val key: String? = null,
    @SerializedName("rawType") val rawType: String? = null
) : DataEntity() {
    @Transient private val classModelName: String = "licenseKey"


}

