/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents a list of LicenseKey entities.
 * @param count 
 * @param href 
 * @param licenseKey 
 */
data class LicenseKeys(
    @SerializedName("count") override val count: Int? = null,
    @SerializedName("href") override val href: String? = null,
    @SerializedName("licenseKey") val licenseKey: List<LicenseKey>? = null
) : ListEntity<LicenseKey>() {
    @Transient private val classModelName: String = "licenseKeys"

    override fun items(): List<LicenseKey> {
        if (licenseKey == null)
            return emptyList()
        return licenseKey
    }


}

