/**
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package org.jetbrains.teamcity.rest.models

import com.google.gson.annotations.SerializedName
import org.jetbrains.teamcity.rest.base.*
import org.jetbrains.teamcity.rest.infrastructure.ApiClient
import org.jetbrains.teamcity.rest.infrastructure.RequestConfig
import java.time.LocalDateTime

/**
Represents various details of this server including installation version.
 * @param version 
 * @param versionMajor 
 * @param versionMinor 
 * @param startTime 
 * @param currentTime 
 * @param buildNumber 
 * @param buildDate 
 * @param internalId 
 * @param role 
 * @param webUrl 
 * @param projects 
 * @param vcsRoots 
 * @param builds 
 * @param users 
 * @param userGroups 
 * @param agents 
 * @param buildQueue 
 * @param agentPools 
 * @param investigations 
 * @param mutes 
 */
data class Server(
    @SerializedName("version") val version: String? = null,
    @SerializedName("versionMajor") val versionMajor: Int? = null,
    @SerializedName("versionMinor") val versionMinor: Int? = null,
    @SerializedName("startTime") val startTime: String? = null,
    @SerializedName("currentTime") val currentTime: String? = null,
    @SerializedName("buildNumber") val buildNumber: String? = null,
    @SerializedName("buildDate") val buildDate: String? = null,
    @SerializedName("internalId") val internalId: String? = null,
    @SerializedName("role") val role: String? = null,
    @SerializedName("webUrl") val webUrl: String? = null,
    @SerializedName("projects") val projects: Href? = null,
    @SerializedName("vcsRoots") val vcsRoots: Href? = null,
    @SerializedName("builds") val builds: Href? = null,
    @SerializedName("users") val users: Href? = null,
    @SerializedName("userGroups") val userGroups: Href? = null,
    @SerializedName("agents") val agents: Href? = null,
    @SerializedName("buildQueue") val buildQueue: Href? = null,
    @SerializedName("agentPools") val agentPools: Href? = null,
    @SerializedName("investigations") val investigations: Href? = null,
    @SerializedName("mutes") val mutes: Href? = null
) : DataEntity() {
    @Transient private val classModelName: String = "server"


}

